
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label lblSubject;
	private global::Gtk.Entry txtSubject;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label lblMessage;
	private global::Gtk.Entry txtMessage;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label lblDuration;
	private global::Gtk.SpinButton spinbutton1;
	private global::Gtk.Label lblSeconds;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label lblRecipient;
	private global::Gtk.ComboBoxEntry txtRecipient;
	private global::Gtk.Button btnSend;
	private global::Gtk.Label txtStatus;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("KodIM");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.lblSubject = new global::Gtk.Label ();
		this.lblSubject.Name = "lblSubject";
		this.lblSubject.LabelProp = global::Mono.Unix.Catalog.GetString ("Subject");
		this.hbox4.Add (this.lblSubject);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblSubject]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.txtSubject = new global::Gtk.Entry ();
		this.txtSubject.CanFocus = true;
		this.txtSubject.Name = "txtSubject";
		this.txtSubject.IsEditable = true;
		this.txtSubject.InvisibleChar = '•';
		this.hbox4.Add (this.txtSubject);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.txtSubject]));
		w2.Position = 1;
		this.vbox3.Add (this.hbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lblMessage = new global::Gtk.Label ();
		this.lblMessage.Name = "lblMessage";
		this.lblMessage.LabelProp = global::Mono.Unix.Catalog.GetString ("Message");
		this.hbox5.Add (this.lblMessage);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblMessage]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.txtMessage = new global::Gtk.Entry ();
		this.txtMessage.CanFocus = true;
		this.txtMessage.Name = "txtMessage";
		this.txtMessage.IsEditable = true;
		this.txtMessage.InvisibleChar = '•';
		this.hbox5.Add (this.txtMessage);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.txtMessage]));
		w5.Position = 1;
		this.vbox3.Add (this.hbox5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblDuration = new global::Gtk.Label ();
		this.lblDuration.TooltipMarkup = "Duration (in seconds) to show message.";
		this.lblDuration.Name = "lblDuration";
		this.lblDuration.LabelProp = global::Mono.Unix.Catalog.GetString ("Duration");
		this.hbox1.Add (this.lblDuration);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblDuration]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.spinbutton1 = new global::Gtk.SpinButton (1, 100, 1);
		this.spinbutton1.TooltipMarkup = "Duration (in seconds) to show message.";
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10;
		this.spinbutton1.ClimbRate = 1;
		this.spinbutton1.Numeric = true;
		this.spinbutton1.Value = 10;
		this.hbox1.Add (this.spinbutton1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.spinbutton1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblSeconds = new global::Gtk.Label ();
		this.lblSeconds.TooltipMarkup = "Duration (in seconds) to show message.";
		this.lblSeconds.Name = "lblSeconds";
		this.lblSeconds.LabelProp = global::Mono.Unix.Catalog.GetString ("seconds");
		this.hbox1.Add (this.lblSeconds);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSeconds]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.lblRecipient = new global::Gtk.Label ();
		this.lblRecipient.TooltipMarkup = "The IP or host name of the receiving XBMC/Kodi machine. Type \"all\" to send to all previous recipients.";
		this.lblRecipient.Name = "lblRecipient";
		this.lblRecipient.LabelProp = global::Mono.Unix.Catalog.GetString ("Recipient");
		this.hbox6.Add (this.lblRecipient);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblRecipient]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.txtRecipient = global::Gtk.ComboBoxEntry.NewText ();
		this.txtRecipient.TooltipMarkup = "The IP or host name of the receiving XBMC/Kodi machine. Type \"all\" to send to all previous recipients.";
		this.txtRecipient.Name = "txtRecipient";
		this.hbox6.Add (this.txtRecipient);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.txtRecipient]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.btnSend = new global::Gtk.Button ();
		this.btnSend.TooltipMarkup = "Send the message.";
		this.btnSend.CanFocus = true;
		this.btnSend.Name = "btnSend";
		this.btnSend.UseUnderline = true;
		this.btnSend.Label = global::Mono.Unix.Catalog.GetString ("Send");
		this.hbox6.Add (this.btnSend);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.btnSend]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox3.Add (this.hbox6);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.txtStatus = new global::Gtk.Label ();
		this.txtStatus.Name = "txtStatus";
		this.vbox3.Add (this.txtStatus);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.txtStatus]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 481;
		this.DefaultHeight = 169;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnSend.Clicked += new global::System.EventHandler (this.HandleSend);
		this.btnSend.Activated += new global::System.EventHandler (this.HandleSend);
	}
}
